project_name: terraform-provider-dcos

before:
  hooks: []

builds:
- binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: -s -extldflags "-static"

archives:
  - id: main
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

release:
  github:
  draft: true
  prerelease: auto
