project_name: terraform-provider-dcos

before:
  hooks: []

builds:
- id: terraform-provider-dcos
  binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
    - windows
    - linux
  goarch:
    - amd64
  ldflags: -s -extldflags "-static"
- id: macos
  binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  ldflags: -s -extldflags "-static"
archives:
  - id: main
    builds:
      - linux-win
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

signs:
  - signature: "${artifact}"
    ids:
      - macos # here we filter the macos only build id
    # you'll need to have gon on PATH
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
      - gon.hcl
    artifacts: all

release:
  github:
  draft: true
  prerelease: auto
  ids:
    - main
  extra_files:
    - glob: ./dist/terraform-provider-dcos-darwin-amd64.zip
