project_name: terraform-provider-dcos

before:
  hooks: []

builds:
- id: linux
  binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags: -s -extldflags "-static"
- id: windows
  binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  ldflags: -s -extldflags "-static"
- id: macos
  binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  ldflags: -s -extldflags "-static"
  hooks:
    post: gon gon.hcl

archives:
  - id: binaries
    builds:
      - linux
      - windows
      - macos
    format: binary
  - id: archives
    builds:
      - linux
      - windows
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

release:
  github:
  draft: true
  prerelease: auto
