project_name: terraform-provider-dcos

before:
  hooks: []

builds:
- binary: terraform-provider-dcos
  env:
    - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: -s -extldflags "-static"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - id: main
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

signs:
  - signature: "${artifact}"
    ids:
    - macos # here we filter the macos only build id
    # you'll need to have gon on PATH
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
    - gon.hcl
    artifacts: all

release:
  github:
  draft: true
  prerelease: auto
