language: go
go:
- '1.13'
jobs:
  include:
    - stage: "Lint"
      script:
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.18.0
        - make lint
    - stage: "Test"
      script:
        - make test
    - stage: "Build"
      script:
        - make build
deploy:
- provider: script
  cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux
